config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :users
  resources :departments
  resources :employees
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :employee, dependent: :destroy
  validates :name, presence: true
  end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :department
  validates :name, presence: true
  validates :department_id, presence: true
  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
	validates :email, presence: true
end

app/controllers/application_controller.rb
require 'will_paginate'
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
 def current_user
   if session[:user_id]
     @current_user ||= User.find(session[:user_id])
   else
     @current_user = nil
   end
 end
 def logged_in?
		!!current_user
	end

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:edit, :update, :show, :destroy]

 def index
   @departments = Department.all
 end


 def new
  @department = Department.new
 end
 def show
end
 def create
   @department = Department.new(department_params)
   if @department.save
     flash[:notice] = "Department was successfully created"
     redirect_to department_path(@department)
   else
     render 'new'
   end
   def edit
   end
   def update
     if @department.update(department_params)
      flash[:notice] = "Department was updated"
      redirect_to department_path(@department)
     else
      flash[:notice] = "Department was not updated"
      render 'edit'
     end
    end
  end
  def destroy
    @department.destroy
    flash[:notice] = "Department was deleted"
    redirect_to departments_path
   end


  private
    def department_params
     params.require(:department).permit(:name)
    end
  end
  def set_department
    @department = Department.find(params[:id])
   end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:edit, :update, :show, :destroy]
 def index
   @employees = Employee.all
   if params[:search]
     @employees = Employee.search(params[:search])
   else
     @employees = Employee.all.order('created_at DESC')
   end
   @employees = Employee.paginate(page: params[:page], per_page: 5)
  end

 def new
  @employee = Employee.new
 end
 def show
end

 def create
  @employee = Employee.new(employee_params)

  if @employee.save
    flash[:notice] = "Employee was successfully created"
    redirect_to employee_path(@employee)
  else
    render 'new'
 end

 def edit
 end

 def update
   
   if @employee.update(employee_params)
    flash[:notice] = "Employee was updated"
    redirect_to employee_path(@employee)
   else
    flash[:notice] = "Employee was not updated"
    render 'edit'
   end
  end
end
def destroy
  @employee.destroy
  flash[:notice] = "Employee was deleted"
  redirect_to employees_path
 end


 private
   def employee_params
    params.require(:employee).permit(:name, :active, :department_id)
   end
 end
 def set_employee
   @employee = Employee.find(params[:id])
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/departments/_form.html.erb
<% if @department.errors.any? %>
 <h2>The following errors prevented the department from saving:</h2>
 <ul>
 <% @department.errors.full_messages.each do |msg|%>
 <li><%= msg %></li>
 <% end %>
 </ul>
<% end %>
<%= form_for @department do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>



<% end %>
<%= link_to 'Back', departments_path %>

app/views/departments/edit.html.erb
<h1>Edit Department</h1>

<%= render 'form' %>

app/views/departments/index.html.erb
<h1>Departments</h1>
<p><%= link_to 'Employees', employees_path %></p>
<% if logged_in? %>
<p><%= link_to "Create new department", new_department_path %></p>
<% end %>
<table>
 <tr>
  <th>Name</th>
  <th>Actions</th>
 </tr>
 <% @departments.each do |department| %>
 <tr>
  <td><%= department.name %></td>
  <% if logged_in? %>
  <td><%= link_to 'Edit', edit_department_path(department) %></td>
  <td><%= link_to 'Show', department_path(department) %></td>
  <td><%= link_to 'Delete', department_path(department), method: :delete, data: {confirm: "Are you sure?"} %></td>
  <% end %>
 </tr>
 <% end %>
</table>

app/views/departments/new.html.erb
<h1>Create Department</h1>

<%= render 'form' %>

app/views/departments/show.html.erb
<h1>Showing selected Department</h1>
<p>
 Name: <%= @department.name %>
</p>
<%= link_to 'Back', departments_path %>
<%= link_to "Edit", edit_department_path(@department) %>

app/views/employees/_form.html.erb
<% if @employee.errors.any? %>
<h2>The following errors prevented the employee from saving:</h2>
<ul>
<% @employee.errors.full_messages.each do |msg|%>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>
  <%= form_for @employee do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
    <p>
    <%= f.label :active %>
    <%= f.check_box :active %>
    </p>
    <p>
      <%= f.label :department_id %>
       <%= f.select :department_id, Department.all.collect {|d| [d.name, d.id]} %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
<%= link_to 'Back', employees_path %>

app/views/employees/edit.html.erb
<h1>Edit Employee</h1>

<%= render 'form' %>

app/views/employees/index.html.erb
<!--Search -->
<%= form_tag(employees_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search" %>
<%= submit_tag "Search" %>
<% end %>
<p id="notice"><%= notice %></p>
<!-- Login-->
<% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= link_to "Sing Up", signup_path %> or
  <%= link_to "Log In", login_path %>
<% end %>
<p id=”notice”><%= notice %></p>
<h1>Employees</h1>
<p><%= link_to 'Departments', departments_path %></p>
<% if logged_in? %>
<p>
<%= link_to "Create new employee", new_employee_path %>
</p>
<% end %>
<table>
  <%= will_paginate %>
 <tr>
  <th>ID</th>
  <th>Name</th>
  <th>Active</th>
  <th>Department</th>
  <th>Actions</th>
 </tr>
 <% @employees.each do |employee| %>

 <tr>
  <td><%= employee.id %></td>
  <td><%= employee.name %></td>
  <td><%= employee.active %></td>
  <td><%= employee.department.name %></td>
  <% if logged_in? %>
  <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
  <td><%= link_to 'Show', employee_path(employee) %></td>
  <td><%= link_to 'Delete', employee_path(employee), method: :delete, data: {confirm: "Are you sure?"} %></td>
  <% end %>
 </tr>


 <% end %>
</table>

app/views/employees/new.html.erb
<h1>Create Employee</h1>

<%= render 'form' %>

app/views/employees/show.html.erb
<h1>Showing selected Employee</h1>
<p>
 Name: <%= @employee.name %>
</p>
<p>
 Active: <%= @employee.active %>
</p>
<p>
 Department: <%= @employee.department.name %>
</p>
<%= link_to 'Back', employees_path %>
<%= link_to "Edit", edit_employee_path(@employee) %>

app/views/home/index.html.erb
<h1>Welcome</h1>
<h2>You need to Sign Up or Log In</h2>
<% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= link_to "Sing Up", signup_path %> or
  <%= link_to "Log In", login_path %>
<% end %>
<p id=”notice”><%= notice %></p>
<% if logged_in? %>
<p><%= link_to 'Employees', employees_path %></p>
<p><%= link_to 'Departments', departments_path %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <% flash.each do |name, msg| %>
        <ul>
         <li><%= msg %></li>
        </ul>
    <% end %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p><%= form.label :email %></p>
    <p><%= form.text_field :email %></p>
  </div>

  <div class="field">
    <p><%= form.label :password %></p>
    <p><%= form.password_field :password %></p>
  </div>

  <div class="field">
    <p><%= form.label :password_confirmation %></p>
    <p><%= form.password_field :password_confirmation %></p>
  </div>

  <div class="actions">
    <p><%= form.submit %></p>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', root_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> | <%= link_to 'Back', root_path %>